Fix quaternion format for agent state rotation
Convert Magnum quaternion to [x, y, z, w] list format using quat_to_coeffs()
before setting agent state rotation. This fixes:

TypeError: '_magnum.Quaternion' object is not subscriptable

The habitat_sim AgentState expects rotation as a list of quaternion coefficients,
not a Magnum Quaternion object. Found the correct conversion function
quat_to_coeffs() in habitat_sim.utils.common (used in rearrange_v2 example).